backend:
  name: git-gateway
  branch: master
media_folder: public/assets
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "content/config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: "Keyword"
              name: "keyword"
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "content/meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "content/meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "pages"
    label: "Pages"
    delete: false
    editor:
      preview: false
    files:
      - name: home
        label: Home
        file: content/pages/home.json
        description: Homepage set-up
        fields:
          - name: hero
            label: Hero
            widget: "object"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Paragraph, name: paragraph, widget: string }
              - label: Image
                name: image
                widget: image
                media_folder: /images
                default: /images/buildings.png
                choose_url: false
              - { label: "Button text", name: text, widget: string }
              - {
                  label: "Button path",
                  name: path,
                  widget: string,
                  hint: "Don't add the trailing /",
                }
          - name: subhero
            label: Sub Hero
            widget: "object"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Paragraph, name: paragraph, widget: string }
              - label: Image
                name: image
                widget: image
                media_folder: /images
                default: /images/financial-institutions.jpg
                choose_url: false
          - name: featuresgrid
            label: Features Grid
            widget: "object"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Paragraph, name: paragraph, widget: string }
              - name: features
                label: Features
                widget: list
                label_singular: field
                summary: "{{fields.heading}}"
                fields:
                  - { label: Heading, name: heading, widget: string }
                  - { label: Paragraph, name: paragraph, widget: string }
                  - label: Icon
                    name: icon
                    widget: image
                    media_folder: /icons
                    default: /icons/globe.png
                    choose_url: false
          - name: split
            label: Split section
            widget: "list"
            label_singular: section
            summary: "{{fields.heading}}"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Paragraph, name: paragraph, widget: string }
              - label: Image
                name: image
                widget: image
                media_folder: /images
                default: "/images/financial-institutions.jpg"
                choose_url: false
          - name: featureslist
            label: Features List
            widget: "object"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Paragraph, name: paragraph, widget: string }
              - name: features
                label: Features
                widget: list
                label_singular: field
                summary: "{{fields.heading}}"
                fields:
                  - { label: Heading, name: heading, widget: string }
                  - { label: Paragraph, name: paragraph, widget: string }
          - name: faq
            label: FAQ
            widget: "object"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Paragraph, name: paragraph, widget: string }
              - name: questions
                label: Questions
                widget: list
                label_singular: question
                summary: "{{fields.question}}"
                fields:
                  - { label: Question, name: question, widget: string }
                  - { label: Answer, name: answer, widget: string }
          - name: cta
            label: CTA
            widget: "object"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: "Button text", name: text, widget: string }
              - {
                  label: "Button path",
                  name: path,
                  widget: string,
                  hint: "Don't add the trailing /",
                }
      - name: about
        label: About
        file: "content/pages/about.json"
        description: "About page set-up"
        fields:
          - name: title
            label: Title
            widget: "object"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Paragraph, name: paragraph, widget: string }
          - name: split
            label: Split section
            widget: "list"
            label_singular: section
            summary: "{{fields.heading}}"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Paragraph, name: paragraph, widget: string }
              - label: Image
                name: image
                widget: image
                media_folder: /images
                default: "/images/financial-institutions.jpg"
                choose_url: false
          - name: timeline
            label: Timeline
            widget: "object"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Paragraph, name: paragraph, widget: string }
              - name: steps
                label: Steps
                widget: "object"
                label_singular: step
                summary: "{{fields.heading}}"
                fields:
                  - { label: Heading, name: heading, widget: string }
                  - { label: Paragraph, name: paragraph, widget: string }
      - name: contact
        label: Contact
        file: "content/pages/contact.json"
        description: "Contact page set-up"
        fields:
          - name: title
            label: Title
            widget: "object"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Paragraph, name: paragraph, widget: string }

  - name: "posts"
    label: "Posts"
    folder: "content/posts/"
    media_folder: public/assets/posts
    public_folder: /assets/posts
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"
